// Barrel file — re-exports from domain modules
export { store } from './core';
export {
  getProject,
  addProject,
  removeProject,
  removeProjectWithTasks,
  updateProject,
  getProjectPath,
  getProjectBranchPrefix,
  pickAndAddProject,
  validateProjectPaths,
  relinkProject,
  isProjectMissing,
  PASTEL_HUES,
} from './projects';
export {
  loadAgents,
  addAgentToTask,
  markAgentExited,
  restartAgent,
  switchAgent,
  addCustomAgent,
  removeCustomAgent,
  updateCustomAgent,
} from './agents';
export {
  createTask,
  closeTask,
  retryCloseTask,
  mergeTask,
  pushTask,
  updateTaskName,
  updateTaskBranch,
  updateTaskNotes,
  sendPrompt,
  setLastPrompt,
  clearInitialPrompt,
  clearPrefillPrompt,
  setPrefillPrompt,
  reorderTask,
  spawnShellForTask,
  runBookmarkInTask,
  closeShell,
  hasDirectTask,
  collapseTask,
  uncollapseTask,
  getGitHubDropDefaults,
  setNewTaskDropUrl,
  setNewTaskPrefillPrompt,
  setPlanContent,
} from './tasks';
export {
  setActiveTask,
  setActiveAgent,
  navigateTask,
  navigateAgent,
  moveActiveTask,
  toggleNewTaskDialog,
} from './navigation';
export {
  registerFocusFn,
  unregisterFocusFn,
  triggerFocus,
  registerAction,
  unregisterAction,
  triggerAction,
  getTaskFocusedPanel,
  setTaskFocusedPanel,
  focusSidebar,
  unfocusSidebar,
  unfocusPlaceholder,
  navigateRow,
  navigateColumn,
  setPendingAction,
  clearPendingAction,
  toggleHelpDialog,
  toggleSettingsDialog,
  toggleFileBrowser,
  sendActivePrompt,
  setSidebarFocusedProjectId,
} from './focus';
export type { PanelId, PendingAction } from './types';
export { saveState, loadState } from './persistence';
export {
  getFontScale,
  adjustFontScale,
  resetFontScale,
  getGlobalScale,
  adjustGlobalScale,
  resetGlobalScale,
  getPanelSize,
  setPanelSizes,
  toggleSidebar,
  toggleArena,
  setTerminalFont,
  setThemePreset,
  setAutoTrustFolders,
  setShowPlans,
  setShowPromptInput,
  setDesktopNotificationsEnabled,
  setInactiveColumnOpacity,
  setEditorCommand,
  setDockerImage,
  setDockerAvailable,
  setWindowState,
} from './ui';
export {
  getTaskDotStatus,
  markAgentOutput,
  clearAgentActivity,
  getAgentOutputTail,
  stripAnsi,
  onAgentReady,
  offAgentReady,
  normalizeForComparison,
  looksLikeQuestion,
  isTrustQuestionAutoHandled,
  isAutoTrustSettling,
  isAgentAskingQuestion,
  startTaskStatusPolling,
  stopTaskStatusPolling,
  rescheduleTaskStatusPolling,
} from './taskStatus';
export type { TaskDotStatus } from './taskStatus';
export { showNotification, clearNotification } from './notification';
export { getCompletedTasksTodayCount, getMergedLineTotals } from './completion';
export {
  createTerminal,
  closeTerminal,
  updateTerminalName,
  syncTerminalCounter,
} from './terminals';
export { startRemoteAccess, stopRemoteAccess, refreshRemoteStatus } from './remote';
